"""create nutrition table

Revision ID: 7740d6944dc1
Revises: 23cee5c9119c
Create Date: 2026-09-06 00:15:43.605527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7740d6944dc1'
down_revision: Union[str, Sequence[str], None] = '23cee5c9119c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=100), nullable=False),
    sa.Column('serving_size_g', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbohydrates_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_name')
    )
    op.create_index(op.f('ix_nutrition_id'), 'nutrition', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutrition_id'), table_name='nutrition')
    op.drop_table('nutrition')
    # ### end Alembic commands ###
