"""link foods to analyses

Revision ID: 89e2e05cee75
Revises: 4e63cf85b5c1
Create Date: 2026-09-06 08:47:55.500879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e2e05cee75'
down_revision: Union[str, Sequence[str], None] = '4e63cf85b5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Add the column temporarily as nullable so existing rows can be updated.
    op.add_column(
        "foods",
        sa.Column("analysis_id", sa.Integer(), nullable=True),
    )

    # Create an analysis record for existing test detections.
    op.execute(
        """
        INSERT INTO analyses (image_id)
        VALUES ('legacy-test-analysis')
        ON CONFLICT (image_id) DO NOTHING
        """
    )

    # Link existing food detections to that analysis.
    op.execute(
        """
        UPDATE foods
        SET analysis_id = (
            SELECT id
            FROM analyses
            WHERE image_id = 'legacy-test-analysis'
        )
        WHERE analysis_id IS NULL
        """
    )

    # Now that every existing row has an analysis_id, make it required.
    op.alter_column(
        "foods",
        "analysis_id",
        existing_type=sa.Integer(),
        nullable=False,
    )

    op.create_index(
        op.f("ix_foods_analysis_id"),
        "foods",
        ["analysis_id"],
        unique=False,
    )

    op.create_foreign_key(
        None,
        "foods",
        "analyses",
        ["analysis_id"],
        ["id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'foods', type_='foreignkey')
    op.drop_index(op.f('ix_foods_analysis_id'), table_name='foods')
    op.drop_column('foods', 'analysis_id')
    # ### end Alembic commands ###
